---
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/mock?allowPublicKeyRetrieval=true&useSSL=false"
    username: "root"
    password: "1234"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        format_sql: true
        dialect: "org.hibernate.dialect.MySQL8Dialect"
